### PR TITLE
Move `html-cleaner` from app namspace to library

### PR DESCRIPTION
**Pull request by wmontwe**
This should better reflect it's purpose as it is not an app, but rather a library.

### CODE REVIEW

**Comment by cketti** [comment]
+1 for moving. But why "library" and not a feature module?

**Comment by wmontwe** [comment]
I took `library` because it serves a supporting role in cleaning up HTML, rather than being a core feature integral to the app's functionality.

**Comment by cketti** [comment]
I guess my question is: What's the advantage of having an additional namespace? 

Do we then also move e.g. `:feature:autodiscovery:autoconfig` there? 

Will having two namespaces with fuzzy criteria on what goes where make it harder to find things? Or do we always use IDE functionality to search anyway? If so, why bother with having an additional namespace?

Maybe we could reserve "library" for when we actually want to publish a library for others to use.

**Comment by wmontwe** [comment]
:feature:autodiscovery:autoconfig´ is a library, true.

**Review by cketti — APPROVED** [review]

**Pull request merged**
