### PR TITLE
Add foss and full K-9 Mail flavors

### PR DESCRIPTION
**Pull request by wmontwe**
This adds `foss` and `full` product flavors to K-9 Mail similarly to Thunderbird.

I updated `shipable_builds.yml` to reflect these changes, but it changed several times, so I'm not sure if I found all spots.

### CODE REVIEW

**Review by cketti — APPROVED** [review]
The change to the Gradle file looks good to me. But someone else should have a look at the updated GitHub workflow.

**Comment by kewisch** [comment]
@wmontwe Workflow run looks fine from what I can tell. Did you do a test run on your repo? If not I'm happy to take care. Can you also update `scripts/setup_release_automation` to include the foss/full flavors for k9mail?

**Comment by wmontwe** [comment]
@kewisch I disabled GitHub actions for my repo as the environment setup is missing. So not tested.

**Comment by wmontwe** [comment]
@kewisch updated

**Review by kewisch — APPROVED** [review]
The signing environments need an update as noted on Matrix:

```diff
diff --git a/scripts/setup_release_automation b/scripts/setup_release_automation
index de931a293..5aa43218b 100644
--- a/scripts/setup_release_automation
+++ b/scripts/setup_release_automation
@@ -95,11 +95,19 @@ CHANNEL_ENVIRONMENTS = {


 SIGNING_ENVIRONMENTS = {
-    "k9mail_release_default": {
+    "k9mail_release_foss": {
         "props": "k9.release.signing.properties",
         "branch": "release",
     },
-    "k9mail_beta_default": {
+    "k9mail_release_full": {
+        "props": "k9.release.signing.properties",
+        "branch": "release",
+    },
+    "k9mail_beta_foss": {
+        "props": "k9.release.signing.properties",
+        "branch": "beta",
+    },
+    "k9mail_beta_full": {
         "props": "k9.release.signing.properties",
         "branch": "beta",
     },
```

r+ with those changes

**Comment by wmontwe** [comment]
Fixed

**Pull request merged**
