### PR TITLE
Add CHANGELOG.md

### LINKED ISSUE #7925: Add Changelog to document project changes
We want to introduce a changelog for Thunderbird for Android and K-9 Mail. It will serve as a base for creating the project’s release notes and document user facing version changes.

We will follow the specification provided by [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), which is widely used to document project changes. The specification provides a standardized format for maintaining changelogs.

### Current state (2024-06-18): 

We use the existing xml based changelog and update it reqularly until we have a ticks all the boxes version. This means:

- [x] Link the existing XML in the readme: #7975
- [x] Update the XML changelog whenever there is a user facing change
- [x] Enforce update via CI

### PR DESCRIPTION
**Pull request by wmontwe**
Added placeholder for the app versioning documentation: #7928

Fixes #7925

### CODE REVIEW

**Comment by cketti** [comment]
This seems premature. Without any tooling in place this is one more changelog we have to maintain (or one that will diverge from the others if we don't).

**Comment by wmontwe** [comment]
> This seems premature. Without any tooling in place this is one more changelog we have to maintain (or one that will diverge from the others if we don't).

What kind of tooling do you imagine?

**Comment by cketti** [comment]
I added a [comment](https://github.com/thunderbird/thunderbird-android/issues/7925#issuecomment-2165888064) to #7925.

**Comment by wmontwe** [comment]
Closed until there is a solution that ticks all the boxes.

**Pull request closed without merging**
