### PR TITLE
Improve French translation

### PR DESCRIPTION
**Pull request by Massedil**
poussé => notifications instantanées (Push)
scrutation => synchronisation
notification continue => notification permanente

### CODE REVIEW

**Comment by wmontwe** [comment]
@Massedil We maintain our translations in Weblate. Could you please update the French translations there instead?

**Comment by Massedil** [comment]
For what I see, it is very slow. I can only make "suggestion". I have to search string one by one. All changes are not grouped together for consistant review. How can I do it quicker ?

**Comment by Massedil** [comment]
@wmontwe I think I have "suggested" everything. Can you confirm it is ok for you ?

**Comment by wmontwe** [comment]
@Massedil Thank you. Your suggestions are being reviewed at Weblate.

**Pull request closed without merging**
