### PR TITLE
Update listing screen shots for f-droid

### PR DESCRIPTION
**Pull request by inattee**
Please ensure that your pull request meets the following requirements - thanks!

- Does not contain merge commits. Rebase instead.
- Contains commits with descriptive titles.
- New code is written in Kotlin whenever possible.
- Follows our existing codestyle (`gradlew spotlessCheck` to check and `gradlew spotlessApply` to format your source code; will be checked by CI).
- Does not break any unit tests (`gradlew testDebugUnitTest`; will be checked by CI).
- Uses a descriptive title; don't put issue numbers in there.
- Contains a reference to the issue that it fixes (e.g. _Closes #XXX_ or _Fixes #XXX_) in the body text.
- For cosmetic changes add one or multiple images, if possible.

Finally, please replace this template text with a description of the change and additional context if necessary.

### CODE REVIEW

**Comment by kewisch** [comment]
@inattee Thank you! Could you export these as 2x so they have 2160px width?

**Comment by kewisch** [comment]
The play store screenshots should also be at that size, this helps with devices that have higher DPI.

**Comment by inattee** [comment]
Sounds good, I'll re-export the files from Figma and update across everything.

**Comment by kewisch** [comment]
I believe all screenshots are taken care of in the two other PRs, closing this one

**Pull request closed without merging**
