### PR TITLE
IMAP: Change EXPUNGE behavior after moving a message

### LINKED ISSUE #7721: IMAP: Delete (move to trash) no longer issues EXPUNGE command
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.712

### Where did you get the app from?

Other

### Android version

12 and 14 - Manufacturer Shipped (Samsung) 

### Device model

Samsung Galaxy Tab S4/9 and phone S10+

### Steps to reproduce

Delete a message (say from Inbox) using K9 Client

### Expected behavior

The message is moved (ie: deleted from Inbox) and placed in Deleted Items (Trash) 

### Actual behavior

In version 6.711 deletion works as expected.  
In version 6.712 a copy is placed in Deleted Items and the original email only marked for deletion in Inbox, when viewed on Webmail.  It no longer displays in K9, however the email still counts towards the number of emails held in the K9 Inbox. (Probably the move is performed but the delete from Inbox partially fails - marked for delete rather than deleted).

The Server is running legacy software from a company that is no longer trading, so the change in 6.712 'Added support for the IMAP MOVE extension' may be the root cause.  I am unable to update the software if this new IMAP extension was added after the last server software release.  

Accepting that a move to a new platform is ultimately inevitable, but is a longer term requirement,  is it possible to detect the failure of the new command (or test whether the server supports the command) and fall back/revert to the previous method if not - which has been working perfectly for a long time!?

A debug log of a successful deletion under 6.711 and a subsequent failed deletion after upgrading to 6.712 is attached (APKs retrieved from GitHub Assets)

The issue was discovered when the latest version (6.800) was pushed from the Google Play Store.  The ticket relates to a posting of a similar title in the support forum

### Logs

[V6.711 08-40 k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14614927/V6.711.08-40.k9mail-logs.txt)
[V6.712 08-50 k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/14614929/V6.712.08-50.k9mail-logs.txt)

### PR DESCRIPTION
**Pull request by cketti**
Fixes #7721

### CODE REVIEW

**Review by wmontwe — COMMENTED** [review]
Looking at this makes we wonder if we need to check if the server is supporting the expunge operation, e.g. `Backend.supportsExpunge`. Also reading the `Account` class, it seems `var expungePolicy = Expunge.EXPUNGE_IMMEDIATELY` is always enabled and not easy for me to figure out when and where it is changed according to the server capabilities.

**Comment by cketti** [comment]
> Looking at this makes we wonder if we need to check if the server is supporting the expunge operation, e.g. Backend.supportsExpunge.

Long-term, almost all of the expunge-related code should be moved to the IMAP backend. It's an IMAP-only feature.

The EXPUNGE command (purge all messages that are marked as deleted) itself is part of the IMAP specification. The UID EXPUNGE command (purge a specific message; not touching other messages that are marked as deleted) is an optional extension.

> Also reading the Account class, it seems var expungePolicy = Expunge.EXPUNGE_IMMEDIATELY is always enabled and not easy for me to figure out when and where it is changed according to the server capabilities.

The default value is always `EXPUNGE_IMMEDIATELY`. It's never set based on server capabilities. Non-IMAP accounts ignore this setting.

The setting can be changed under *Settings → [Account] → Fetching mail → Erase deleted messages on server*.

**Comment by wmontwe** [comment]
Thanks for the explanation. I was especially looking at the `expungeUids` call and trying to understand what the code is doing. From my understand it should check if the server is supporting the IMAP UID EXPUNGE extension. When exploring the code, there is a `ImapConnection.isUidPlusCapable` that is checked, could I assume this is the IMAP UID EXPUNGE extension? I also found a `ImapConnection.hasCapability' how does this relate to the `capable` flags?

**Comment by cketti** [comment]
> I was especially looking at the `expungeUids` call and trying to understand what the code is doing. From my understand it should check if the server is supporting the IMAP UID EXPUNGE extension. When exploring the code, there is a `ImapConnection.isUidPlusCapable` which is checked, could I assume this is the IMAP UID EXPUNGE extension?

UID EXPUNGE is defined in [RFC 4315, section 2.1](https://datatracker.ietf.org/doc/html/rfc4315#section-2.1). The associated capability string is `UIDPLUS`. So yes, this is checking if the app can use the UID EXPUNGE command.

> I also found an `ImapConnection.hasCapability` how does this relate to the `capable` flags?

`ImapConnection.isUidPlusCapable` and `ImapConnection.hasCapability("UIDPLUS")` are roughly doing the same thing. Do we need two ways to do the same thing? Probably not. But I'd rather not change this in a bugfix release.

**Review by wmontwe — APPROVED** [review]
I think we should find a better way to deal with the capabilities, but for this bug fix it's probably fine.

**Pull request merged**
