### PR TITLE
Move unread widget to separate module

### PR DESCRIPTION
**Pull request by wmontwe**
This moves the unread widget to it's own module to shrink down the `:app:common` module.

Tasks once reviewed:

- [x] Lock Weblate
- [x] Pull latest translations from weblate, check if moved resources are affected and update this branch
- [ ] After Merge update weblate to pickup the new module
- [ ] Unlock Weblate

### CODE REVIEW

**Comment by cketti** [comment]
Apologies. I merged the translation changes from Weblate before opening this pull request and realizing it moves strings to a different location.

But the merge conflict is an indicator that this change to translated strings in the repository could have lost changes made to translations on Weblate. I think whenever we move strings we need to lock translations on Weblate first, then merge all outstanding changes from Weblate, then create and merge the pull request. Otherwise there's always the potential for conflicts.

**Comment by wmontwe** [comment]
> But the merge conflict is an indicator that this change to translated strings in the repository could have lost changes made to translations on Weblate. I think whenever we move strings we need to lock translations on Weblate first, then merge all outstanding changes from Weblate, then create and merge the pull request. Otherwise there's always the potential for conflicts.

That is expected, that's why I added the todos. I just didn't wan't to lock weblate for the time this pull-request is waiting for approval.

**Comment by cketti** [comment]
This PR changes the package name of `UnreadWidgetProvider`. That leads to existing widgets no longer working. See https://github.com/thunderbird/thunderbird-android/blob/33251e6a0fe1388dcc2a46fe71977795f68ee261/app/common/src/main/java/com/fsck/k9/provider/UnreadWidgetProvider.kt#L25-L26

I propose the following change to deal with this: https://github.com/cketti/k-9/commit/f059a3c9494506271fea3b44dd4ef42e17f42647

**Comment by wmontwe** [comment]
I guess then it's better I move the widget to it's final destination: `:feature:widget:unread`

**Comment by wmontwe** [comment]
> I propose the following change to deal with this: https://github.com/cketti/k-9/commit/f059a3c9494506271fea3b44dd4ef42e17f42647

These changes break the widget. I'll have a look next week.

**Pull request merged**
