### PR TITLE
Increase targetSdkVersion to 33

### PR DESCRIPTION
**Pull request by cketti**
Also, add [POST_NOTIFICATIONS](https://developer.android.com/reference/android/Manifest.permission#POST_NOTIFICATIONS) permission to the Android manifest.

### CODE REVIEW

**Review by wmontwe — APPROVED** [review]
👍

**Comment by Goooler** [comment]
The usage of `AlarmManager` should be migrated

https://github.com/thunderbird/thunderbird-android/blob/8f06c24bd3b6cc04abcda86de0b63ad420764781/app/core/src/main/java/com/fsck/k9/helper/AlarmManagerCompat.kt#L10

See https://developer.android.com/about/versions/14/changes/schedule-exact-alarms

**Comment by Goooler** [comment]
> the permission introduced in Android 12 for apps to schedule exact alarms, is no longer being pre-granted to most newly installed apps targeting Android 13 and higher (will be set to denied by default)

After bumping to `targetSdk` 33, this permission will not be granted automatically on Android 14 devices for clean installations.

**Comment by cketti** [comment]
I currently don't see a way around using exact alarms. Staying below `targetSdkVersion 33 ` isn't an option either. So I'll merge this change and we'll deal with Android 14 separately.

I created issue #7363 to keep track of the problem.

**Pull request merged**
