### PR TITLE
Fix permission screen back behavior

### PR DESCRIPTION
**Pull request by wmontwe**
Prevent back navigation on permission screen to not create accounts twice or get stuck on the account created screen.

### CODE REVIEW

**Comment by cketti** [comment]
When account setup is complete, all screens should probably also be popped of the back stack.

**Comment by wmontwe** [comment]
I changed it to pop the back stack, but the behavior is now: press back -> leave app -> enter app again -> permission screen is gone and you land in the inbox.

**Comment by cketti** [comment]
My suggestion would be:
a) When permissions have already been granted, go to the message list.
b) When permissions haven't been granted yet, display a dialog asking if the user wants to skip granting permissions. If yes, go to the message list. If no, stay on screen.

**Comment by cketti** [comment]
> a) this screen is only shown on first use of the app

I meant when a user used the permission screen to grant the permissions, then instead of using the "Next" button they (maybe accidentally) use the back button.

> b) at the moment we don't have Compose Dialogs available in the design system

I am aware. We could add one. It's an edge case users should rarely run into. Anyway, this could be a "proper" fix for later.

For now we could just do what you initially had (ignore the back button). My suggestion was to pop the back stack in addition to that. Both to free resources and so we can't accidentally leave another way open to navigate back to the account setup screens.

**Comment by wmontwe** [comment]
Reverted changes

**Review by cketti — APPROVED** [review]

**Pull request merged**
