### PR TITLE
Fix `InputStream` implementations

### PR DESCRIPTION
**Pull request by cketti**
`FixedLengthInputStream` contained a `while` loop that together with a bug in `PeekableInputStream` could have lead to an endless loop. I couldn't find a way to trigger this in the app. But getting rid of the loop seems like a good idea anyway.

### CODE REVIEW

**Comment by williamdes** [comment]
> `FixedLengthInputStream` contained a `while` loop that together with a bug in `PeekableInputStream` could have lead to an endless loop. I couldn't find a way to trigger this in the app. But getting rid of the loop seems like a good idea anyway.

Ha !
This could be what I was talking about in #6862
And it could be what drains my battery (soooo often) reported in #4747

**Comment by cketti** [comment]
Like I said, I couldn't find a code path that would actually trigger this bug. So I doubt it's the cause of #4747.

**Review by wmontwe — APPROVED** [review]
LGTM

**Comment by williamdes** [comment]
> Like I said, I couldn't find a code path that would actually trigger this bug. So I doubt it's the cause of #4747.

I am really starting to think that https://github.com/thundernest/k-9/commit/07985f706688f64197dc45fef74a38f7dbbec92b did kill the bug
It's been more than a week and I did not see my phone go wild since then

**Pull request merged**
